players_to_check = {
    "#JPCVVPYY":"KalKarreth",
    "#JLRGG0RL":"Kal",
    "#YL02LQGY":"Naesm",
    "#92GJJ99L":"iTzu",
    "#998G09JQQ":"eVe MAXI",
    "#CY8UL0R9":"iTzo",
    "#28QQU9CU":"CarbonFin",
    "#22YPRR8Q2":"Okumura"
}

clans_to_check = {
    "#2R9LQRLY": "B-Bros",
    "#8ULL0ULU" : "Official",
    "#8QJY9V8P" : "Tribe Gaming2?",
    "#2PC0GJVCC": "Darkest",
    "#PC82C20L": "x6tence",
    "#9LLUUYJQ": "",
    "#9G2QU8YG": "Nova",
    "#20Y9LGU8": "Resistance",
    "#9VVYLG92": "M.K.M.A",
    "#8CYJLY9U": "",
    "#PGV89VRY": "INTZ",
    "#9VPR98RG": "Death Dealers",
    "#2882VCJRJ": "SpaceStation",
    "#9GP02C22": "Tribe Gaming",
    "#P8PY88VU": "INDIAN CLASH 2",
    "#9JP0CQR2": "Saudia Arabian Team",
    "#9ULLP8GJ": "",
    "#U8009PY": "TownHall.Legend",
    "#P9CQG9P8": "Demons Lair",
    "#2PYPYCP2R": "eleVen Original",
    "#GQYPV2RG": "blaze JP",
    "#P222C9Y": "Word Top Korea",
    "#P8022UUG": "Vatang",
    "#222C08VQV": "MCES",
    "#2CULVUJ0": "War Agency",
    "#28C8V8GP2": "Tribe Academy",
    "#2JPVRVYR": "Legion Divina",
    "#2U2CYPQ8": "OneHive",
    "#2LJCUU0J": "WHF Rising",
    "#8ULGUJ92": "Zombie Doom",
    "#282R02YCQ": "Queen Walkers",
    "#990VY99V": "los zetas",
    "#280V0VYL": "Reddit Vortex",
    "#P8PLLJUL": "!CruncHTimE!",
    "#288YPPP8P": "Orphan eSports",
}